### ISSUE TITLE
Error while writing on a characteristic

### ISSUE THREAD

**Issue by TomDemulierChevret** [don/cordova-plugin-ble-central#317]
Hi,

When I'm trying to write data to a characteristic (with the Ionic 2 wrapper around your plugin) :  
```
let key: Uint8Array = new Uint8Array(5);
key[0] = 0x80;
key[1] = 0XBE;
key[2] = 0xF5;
key[3] = 0xAC;
key[4] = 0xFF;
BLE.write(device.id, 'fffffff5-00f7-4000-b000-000000000000', 'fffffff0-00f7-4000-b000-000000000000', key.buffer)
```

I'm getting the following error :
```
10-07 14:05:40.682: E/PluginManager(31860): Uncaught exception from plugin
10-07 14:05:40.682: E/PluginManager(31860): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.bluetooth.BluetoothGattService.getCharacteristics()' on a null object reference
10-07 14:05:40.682: E/PluginManager(31860): 	at com.megster.cordova.ble.central.Peripheral.findWritableCharacteristic(Peripheral.java:559)
10-07 14:05:40.682: E/PluginManager(31860): 	at com.megster.cordova.ble.central.Peripheral.writeCharacteristic(Peripheral.java:525)
10-07 14:05:40.682: E/PluginManager(31860): 	at com.megster.cordova.ble.central.Peripheral.processCommands(Peripheral.java:637)
10-07 14:05:40.682: E/PluginManager(31860): 	at com.megster.cordova.ble.central.Peripheral.queueCommand(Peripheral.java:611)
10-07 14:05:40.682: E/PluginManager(31860): 	at com.megster.cordova.ble.central.Peripheral.queueWrite(Peripheral.java:582)
10-07 14:05:40.682: E/PluginManager(31860): 	at com.megster.cordova.ble.central.BLECentralPlugin.write(BLECentralPlugin.java:403)
10-07 14:05:40.682: E/PluginManager(31860): 	at com.megster.cordova.ble.central.BLECentralPlugin.execute(BLECentralPlugin.java:179)
10-07 14:05:40.682: E/PluginManager(31860): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
10-07 14:05:40.682: E/PluginManager(31860): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
10-07 14:05:40.682: E/PluginManager(31860): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
10-07 14:05:40.682: E/PluginManager(31860): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
10-07 14:05:40.682: E/PluginManager(31860): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
10-07 14:05:40.682: E/PluginManager(31860): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-07 14:05:40.682: E/PluginManager(31860): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
10-07 14:05:40.682: E/PluginManager(31860): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-07 14:05:40.682: E/PluginManager(31860): 	at android.os.Looper.loop(Looper.java:154)
10-07 14:05:40.682: E/PluginManager(31860): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

It seem's to be caused by `BluetoothGattService service = gatt.getService(serviceUUID);` (in Peripheral.java) not instantiating the service.
It could be caused by a bad service UUID, but `console.log(JSON.stringify(res, null, 2));` from the peripheral data returned by `connect()` shows the UUID I'm using.

Any insight that could help me solve this problem ?
Thanks in advance.

```
{
  "name": "V.ALRT A2:FE:C1",
  "id": "D0:39:72:A2:FE:C1",
  "advertising": {},
  "rssi": -32,
  "services": [
    "1800",
    "1801",
    "180a",
    "1803",
    "1802",
    "1804",
    "180f",
    "ffffffa0-00f7-4000-b000-000000000000",
    "ffffffe0-00f7-4000-b000-000000000000",
    "fffffff0-00f7-4000-b000-000000000000",
    "ffffccc0-00f7-4000-b000-000000000000"
  ],
  "characteristics": [
    {
      "service": "1800",
      "characteristic": "2a00",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "1800",
      "characteristic": "2a01",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "1800",
      "characteristic": "2a02",
      "properties": [
        "Read",
        "Write"
      ]
    },
    {
      "service": "1800",
      "characteristic": "2a03",
      "properties": [
        "Write"
      ]
    },
    {
      "service": "1800",
      "characteristic": "2a04",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "1801",
      "characteristic": "2a05",
      "properties": [
        "Indicate"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        }
      ]
    },
    {
      "service": "180a",
      "characteristic": "2a23",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "180a",
      "characteristic": "2a24",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "180a",
      "characteristic": "2a25",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "180a",
      "characteristic": "2a26",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "180a",
      "characteristic": "2a27",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "180a",
      "characteristic": "2a28",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "180a",
      "characteristic": "2a29",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "180a",
      "characteristic": "2a2a",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "180a",
      "characteristic": "2a50",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "1803",
      "characteristic": "2a06",
      "properties": [
        "Read",
        "Write"
      ]
    },
    {
      "service": "1802",
      "characteristic": "2a06",
      "properties": [
        "WriteWithoutResponse"
      ]
    },
    {
      "service": "1804",
      "characteristic": "2a07",
      "properties": [
        "Read",
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        }
      ]
    },
    {
      "service": "180f",
      "characteristic": "2a19",
      "properties": [
        "Read",
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        },
        {
          "uuid": "2908"
        }
      ]
    },
    {
      "service": "ffffffa0-00f7-4000-b000-000000000000",
      "characteristic": "ffffffa1-00f7-4000-b000-000000000000",
      "properties": [
        "Read",
        "Write"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "ffffffa0-00f7-4000-b000-000000000000",
      "characteristic": "ffffffa2-00f7-4000-b000-000000000000",
      "properties": [
        "Read"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "ffffffa0-00f7-4000-b000-000000000000",
      "characteristic": "ffffffa3-00f7-4000-b000-000000000000",
      "properties": [
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        },
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "ffffffa0-00f7-4000-b000-000000000000",
      "characteristic": "ffffffa4-00f7-4000-b000-000000000000",
      "properties": [
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        },
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "ffffffa0-00f7-4000-b000-000000000000",
      "characteristic": "ffffffa5-00f7-4000-b000-000000000000",
      "properties": [
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        },
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "ffffffe0-00f7-4000-b000-000000000000",
      "characteristic": "ffffffe1-00f7-4000-b000-000000000000",
      "properties": [
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        },
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "fffffff0-00f7-4000-b000-000000000000",
      "characteristic": "fffffff1-00f7-4000-b000-000000000000",
      "properties": [
        "Read",
        "Write"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "fffffff0-00f7-4000-b000-000000000000",
      "characteristic": "fffffff2-00f7-4000-b000-000000000000",
      "properties": [
        "Read",
        "Write"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "fffffff0-00f7-4000-b000-000000000000",
      "characteristic": "fffffff3-00f7-4000-b000-000000000000",
      "properties": [
        "Write"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "fffffff0-00f7-4000-b000-000000000000",
      "characteristic": "fffffff4-00f7-4000-b000-000000000000",
      "properties": [
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        },
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "fffffff0-00f7-4000-b000-000000000000",
      "characteristic": "fffffff5-00f7-4000-b000-000000000000",
      "properties": [
        "Write"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "fffffff0-00f7-4000-b000-000000000000",
      "characteristic": "fffffff6-00f7-4000-b000-000000000000",
      "properties": [
        "Read",
        "Write"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "fffffff0-00f7-4000-b000-000000000000",
      "characteristic": "fffffff7-00f7-4000-b000-000000000000",
      "properties": [
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        },
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "fffffff0-00f7-4000-b000-000000000000",
      "characteristic": "fffffff8-00f7-4000-b000-000000000000",
      "properties": [
        "Read"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "ffffccc0-00f7-4000-b000-000000000000",
      "characteristic": "ffffccc1-00f7-4000-b000-000000000000",
      "properties": [
        "Read",
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        },
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "ffffccc0-00f7-4000-b000-000000000000",
      "characteristic": "ffffccc2-00f7-4000-b000-000000000000",
      "properties": [
        "Write"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    },
    {
      "service": "ffffccc0-00f7-4000-b000-000000000000",
      "characteristic": "ffffccc3-00f7-4000-b000-000000000000",
      "properties": [
        "Write"
      ],
      "descriptors": [
        {
          "uuid": "2901"
        }
      ]
    }
  ]
}
```

**Comment by don** [comment]
It looks like you have service and characteristic UUIDs switched.

    let serviceUUID = 'fffffff0-00f7-4000-b000-000000000000';
    let characteristicUUID = 'fffffff5-00f7-4000-b000-000000000000';
    BLE.write(device.id, serviceUUID, characteristicUUID, key.buffer);

**Comment by TomDemulierChevret** [comment]
Oh.
I'm definitely dumb.
I was convinced that the arguments order was characteristic then service.

It's working like a charm now.
And I'm gonna hang myself.

**Comment by don** [comment]
Glad it's working.
