### ISSUE TITLE
Cordova-Camera-plugin Plugin manager Error

### ISSUE THREAD

**Issue by premji1528** [don/cordova-plugin-ble-central#406]
Hi, I am New for ionic i just tried to use the camera plugin, now i'm getting Error on it: 

E/PluginManager(15200): Uncaught exception from plugin
E/PluginManager(15200): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:560)
at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:534)
at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:376)
at org.apache.cordova.camera.CameraLauncher.takePicture(CameraLauncher.java:295)
at org.apache.cordova.camera.CameraLauncher.callTakePicture(CameraLauncher.java:275)
 E/PluginManager(15200): 	at org.apache.cordova.camera.CameraLauncher.execute(CameraLauncher.java:184)
 E/PluginManager(15200): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
 E/PluginManager(15200): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
 E/PluginManager(15200): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
 E/PluginManager(15200): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
 E/PluginManager(15200): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
 E/PluginManager(15200): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
 E/PluginManager(15200): 	at android.os.Handler.dispatchMessage(Handler.java:111)
 E/PluginManager(15200): 	at android.os.Looper.loop(Looper.java:207)
 E/PluginManager(15200): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/cr_Ime(15200): updateState: type [0->0], flags [0], show [false], 

My plugins --v:-
"cordova-plugin-camera": "^2.4.0",
"cordova-plugin-compat": "^1.1.0",
![screenshot_2017-05-24-12-21-15-646](https://cloud.githubusercontent.com/assets/8487640/26390317/b5341598-407b-11e7-8b0f-bf3835ea34cc.jpeg)

**Comment by premji1528** [comment]
Finally i tried build the app on Android Studio and disabled instant run, it works good...
