### ISSUE TITLE
Disconnect works from button callback, but hits uncaught exception from interval timer callback

### ISSUE THREAD

**Issue by gpetrowitsch** [don/cordova-plugin-ble-central#799]
Hi,

I have a very annoying problem: My application should disconnect from the BLE device after 30s of no activity from the user (i.e. pressing buttons in the GUI). I also have a "Disconnect" button in my GUI.

If I press this button, disconnect works fine. If I call the same disconnect function in my timer callback, it crashes with an uncaught exception.

This is, what the "Disconnect" button callback looks like:
```
    disconnect: function(e) {
        if (app.peripheral && app.peripheral.id) {
            ble.disconnect(app.peripheral.id, app.showMainPage, app.onError);
        }
        isConnected = false;
    },
```
And this is the callback of my timer (I'm using an interval timer to avoid having to clear and start a timeout timer each time).
Note: I could also have called app.disconnect() here, but this makes no difference.
I also tried to programmatically click the "Disconnect" button in this timer callback, but this also fired the uncaught exception.

```
    checkTimeout: function() {
        if (isConnected) {
            console.log('Timeout counter is ' + timeoutCnt);
            timeoutCnt = timeoutCnt + 1;
            if (timeoutCnt > DISCONNECT_AFTER) {
                console.log('DISCONNECTED AFTER '+DISCONNECT_AFTER+'s');
                // disconnect BLE device
                if (app.peripheral && app.peripheral.id) {
                    ble.disconnect(app.peripheral.id, app.showMainPage, app.onError);
                }
                isConnected = false;
            }
        } else {
            timeoutCnt = 0;
        }
    },

```

This is the log, when disconnect throws the exception:
```
08-15 18:02:52.545: I/chromium(4168): [INFO:CONSOLE(60)] "DISCONNECTED AFTER 30s", source: file:///android_asset/www/js/index.js (60)
08-15 18:02:52.553: D/BLEPlugin(4168): action = disconnect
08-15 18:02:52.554: D/BluetoothGatt(4168): cancelOpen() - device: EB:9E:7C:1B:C2:D1
08-15 18:02:52.560: D/BluetoothGatt(4168): onClientConnectionState() - status=0 clientIf=8 device=EB:9E:7C:1B:C2:D1
08-15 18:02:52.560: D/Peripheral(4168): onConnectionStateChange DISCONNECTED
08-15 18:02:52.561: D/BluetoothGatt(4168): cancelOpen() - device: EB:9E:7C:1B:C2:D1
08-15 18:02:52.566: D/BluetoothGatt(4168): close()
08-15 18:02:52.566: D/BluetoothGatt(4168): unregisterApp() - mClientIf=8
08-15 18:02:52.574: E/PluginManager(4168): Uncaught exception from plugin
08-15 18:02:52.574: E/PluginManager(4168): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGatt.close()' on a null object reference
08-15 18:02:52.574: E/PluginManager(4168): 	at com.megster.cordova.ble.central.Peripheral.disconnect(Peripheral.java:126)
08-15 18:02:52.574: E/PluginManager(4168): 	at com.megster.cordova.ble.central.BLECentralPlugin.disconnect(BLECentralPlugin.java:458)
08-15 18:02:52.574: E/PluginManager(4168): 	at com.megster.cordova.ble.central.BLECentralPlugin.execute(BLECentralPlugin.java:186)
08-15 18:02:52.574: E/PluginManager(4168): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
08-15 18:02:52.574: E/PluginManager(4168): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
08-15 18:02:52.574: E/PluginManager(4168): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
08-15 18:02:52.574: E/PluginManager(4168): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
08-15 18:02:52.574: E/PluginManager(4168): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
08-15 18:02:52.574: E/PluginManager(4168): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
08-15 18:02:52.574: E/PluginManager(4168): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
08-15 18:02:52.574: E/PluginManager(4168): 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-15 18:02:52.574: E/PluginManager(4168): 	at android.os.Looper.loop(Looper.java:203)
08-15 18:02:52.574: E/PluginManager(4168): 	at android.os.HandlerThread.run(HandlerThread.java:61)
08-15 18:02:52.578: D/BluetoothDevice(4168): getName: name = ArduinoRemote
08-15 18:02:52.585: D/WebView(4168): evaluateJavascript=cordova.callbackFromNative('BLE32906418',false,9,[{"name":"ArduinoRemote","id":"EB:9E:7C:1B:C2:D1","errorMessage":"Peripheral Disconnected"}],false);
08-15 18:02:52.624: I/chromium(4168): [INFO:CONSOLE(28)] "
08-15 18:02:52.624: I/chromium(4168): ***** JavaScript Error *****
08-15 18:02:52.624: I/chromium(4168): Uncaught TypeError: Cannot read property 'alert' of undefined
08-15 18:02:52.624: I/chromium(4168): File: cordova.js
08-15 18:02:52.624: I/chromium(4168): Line: 314
08-15 18:02:52.624: I/chromium(4168): Column: 13
08-15 18:02:52.624: I/chromium(4168): Error object: {}", source: file:///android_asset/www/js/onerror.js (28)
08-15 18:02:52.625: I/chromium(4168): [INFO:CONSOLE(314)] "Uncaught TypeError: Cannot read property 'alert' of undefined", source: file:///android_asset/www/cordova.js (314)
08-15 18:02:52.625: I/chromium(4168): [INFO:CONSOLE(45)] "Uncaught TypeError: Cannot read property 'alert' of undefined", source: file:///android_asset/www/js/onerror.js (45)
08-15 18:02:52.625: I/chromium(4168): [INFO:CONSOLE(461)] "Uncaught (in promise) TypeError: Cannot read property 'alert' of undefined", source: file:///android_asset/www/js/index.js (461)

```

**Comment by peitschie** [comment]
This has (hopefully) been fixed by synchronising access to this variable when processing a disconnect command.
